In [11]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt 

# Load and read the data
netflix_df= pd.read_csv('netflix_data.csv')
print(netflix_df)

     show_id     type                                    title  \
0         s1  TV Show                                       3%
1         s2    Movie                                     7:19
2         s3    Movie                                    23:59
3         s4    Movie                                        9
4         s5    Movie                                       21
...      ...      ...                                      ...
7782   s7783    Movie                                     Zozo
7783   s7784    Movie                                   Zubaan
7784   s7785    Movie                        Zulu Man in Japan
7785   s7786  TV Show                    Zumbo's Just Desserts
7786   s7787    Movie  ZZ TOP: THAT LITTLE OL' BAND FROM TEXAS

               director                                               cast  \
0                   NaN  João Miguel, Bianca Comparato, Michel Gomes, R...
1     Jorge Michel Grau  Demián Bichir, Héctor Bonilla, Oscar Serrano, ...
2          Gilbert Chan  Tedd Chan, Stella Chung, Henley Hii, Lawrence ...
3           Shane Acker  Elijah Wood, John C. Reilly, Jennifer Connelly...
4        Robert Luketic  Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...
...                 ...                                                ...
7782        Josef Fares  Imad Creidi, Antoinette Turk, Elias Gergi, Car...
7783        Mozez Singh  Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...
7784                NaN                                            Nasty C
7785                NaN                         Adriano Zumbo, Rachel Khoo
7786           Sam Dunn                                                NaN

             country          date_added  release_year  duration  \
0             Brazil     August 14, 2020          2020         4
1             Mexico   December 23, 2016          2016        93
2          Singapore   December 20, 2018          2011        78
3      United States   November 16, 2017          2009        80
4      United States     January 1, 2020          2008       123
...              ...                 ...           ...       ...
7782          Sweden    October 19, 2020          2005        99
7783           India       March 2, 2019          2015       111
7784             NaN  September 25, 2020          2019        44
7785       Australia    October 31, 2020          2019         1
7786  United Kingdom       March 1, 2020          2019        90

                                            description             genre
0     In a future where the elite inhabit an island ...  International TV
1     After a devastating earthquake hits Mexico Cit...            Dramas
2     When an army recruit is found dead, his fellow...     Horror Movies
3     In a postapocalyptic world, rag-doll robots hi...            Action
4     A brilliant group of students become card-coun...            Dramas
...                                                 ...               ...
7782  When Lebanon's Civil War deprives Zozo of his ...            Dramas
7783  A scrappy but poor boy worms his way into a ty...            Dramas
7784  In this documentary, South African rapper Nast...     Documentaries
7785  Dessert wizard Adriano Zumbo looks for the nex...  International TV
7786  This documentary delves into the mystique behi...     Documentaries

[7787 rows x 11 columns]

In [12]:
#View the first five rows of the df 
print(netflix_df.loc[0:4])

  show_id     type  title           director  \
0      s1  TV Show     3%                NaN
1      s2    Movie   7:19  Jorge Michel Grau
2      s3    Movie  23:59       Gilbert Chan
3      s4    Movie      9        Shane Acker
4      s5    Movie     21     Robert Luketic

                                                cast        country  \
0  João Miguel, Bianca Comparato, Michel Gomes, R...         Brazil
1  Demián Bichir, Héctor Bonilla, Oscar Serrano, ...         Mexico
2  Tedd Chan, Stella Chung, Henley Hii, Lawrence ...      Singapore
3  Elijah Wood, John C. Reilly, Jennifer Connelly...  United States
4  Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...  United States

          date_added  release_year  duration  \
0    August 14, 2020          2020         4
1  December 23, 2016          2016        93
2  December 20, 2018          2011        78
3  November 16, 2017          2009        80
4    January 1, 2020          2008       123

                                         description             genre
0  In a future where the elite inhabit an island ...  International TV
1  After a devastating earthquake hits Mexico Cit...            Dramas
2  When an army recruit is found dead, his fellow...     Horror Movies
3  In a postapocalyptic world, rag-doll robots hi...            Action
4  A brilliant group of students become card-coun...            Dramas

In [15]:
# Subsetting the netflix dataframe rows choosing type movies and some coloumns
netflix_subset= netflix_df[netflix_df['type']=='Movie']
netflix_movies= netflix_subset[['title', 'country', 'genre', 'release_year', 'duration']]
netflix_movies.head(5)

   title        country          genre  release_year  duration
1   7:19         Mexico         Dramas          2016        93
2  23:59      Singapore  Horror Movies          2011        78
3      9  United States         Action          2009        80
4     21  United States         Dramas          2008       123
6    122          Egypt  Horror Movies          2019        95